### ISSUE TITLE
Request adding RSSHub to aosus server

### ISSUE THREAD

**Issue by mosaleh52** [aosus/infrastructure-meta#8]
Her is the docker compose file
https://github.com/DIYgod/RSSHub/blob/master/docker-compose.yml

**Comment by FarisZR** [comment]
I'm not sure if this serves aosus services main goal of improving privacy, this just create an RSS feed for websites without one.

**Comment by mosaleh52** [comment]
It could help to avoid services that Aosus does not have alternative frontends for, such as Discord, Instagram, Telegram, and LinkedIn.

**Comment by FarisZR** [comment]
all of these services will get rate limited quickly, in addition this opens the service to a huge risk of abuse as anybody can enter any link they want.
